name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2

      - name: Setup node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '8.9'

      - name: Restore cache
        uses: actions/cache@v3.3.1
        with:
          path: node_modules
          key: v1-dependencies-${{ hashFiles('package.json') }}
          restore-keys: |
            v1-dependencies-${{ hashFiles('package.json') }}
            v1-dependencies-

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test
